Enhancement/proptype validation responsive modifiers size
Decisiv/styled-components-modifiers pull request #39
Opened 2019-10-22 20:51 UTC by Nauthiz-Jera

## OVERVIEW

PR based on this open Issue:
closes https://github.com/Decisiv/styled-components-modifiers/issues/27

## WHERE SHOULD THE REVIEWER START?

`src/styleModifierPropTypes.ts`
`src/responsiveStyleModifierPropTypes.ts`

## HOW CAN THIS BE MANUALLY TESTED?

- Create a component with modifiers.
- Render the component in an application using an object syntax to declare the modifiers.
- Do not provide a size prop
- Observe no errors and no styles applied.

## ANY NEW DEPENDENCIES ADDED?

No new dependencies

## CHECKLIST

_Be sure all items are_ ✅ _before submitting a PR for review._

- [x] Verify the linter and tests pass: `npm run review`
- [x] Verify this branch is rebased with the latest master

## GIF

_Share a fun GIF to say thanks to your reviewer:_ https://giphy.com

![](https://media.giphy.com/media/xTiTnfkt9wCx4fuWhW/giphy.gif)

2019-11-15 14:02 UTC, andrewtpoe requested changes
This is great work, thank you for contributing!

I've left just a few comments I'd like to see get resolved before this gets merged.

2019-11-15 14:02 UTC, andrewtpoe commented on src/styleModifierPropTypes.ts
> +  // eslint-disable-next-line
This isn't needed.

2019-11-15 14:02 UTC, andrewtpoe commented on src/styleModifierPropTypes.ts
> +  }
Please add a new empty line after this code block.

2019-11-15 14:02 UTC, andrewtpoe commented on src/styleModifierPropTypes.ts
> +    const sizeProp = props.size;
This will work if the size prop is any truthy value, but it is also possible that the size may actually be `undefined`.  Maybe a better check would be `props.hasOwnProperty('size')`. We really only care that the size prop is declared, not what its value is. Please add a test case for this scenario as well.

2019-11-15 14:02 UTC, andrewtpoe commented on src/styleModifierPropTypes.ts
> +      'Invalid Responsive Modifier; size prop must be included when using Responsive Modifiers.',
I think I'd like to change the wording on this error message a bit to be more in line with the other error messages generated for proptype failures. Maybe:

`Invalid responsive prop supplied to <ComponentName>. Prop 'size' must be included when using responsive modifiers. Validation failed.`

2019-11-15 14:02 UTC, andrewtpoe commented on src/__tests__/styleModifierPropTypes.js
> +test('styleModifierPropTypes logs error when no size prop is passed when using responsive modifiers', () => {
💯

2019-11-18 14:05 UTC, Nauthiz-Jera commented
Thanks! Glad to help, I've made the changes per-requested. If there is any other changes you'd like please let me know.

2019-11-20 14:26 UTC, andrewtpoe commented
This code is ready to merge, but doing so will cause a breaking change. Code that was previously ok will now throw PropTypes errors and may break.

This is going to be targeted at v2. The rest of v2 is still being planned, so we are going to sit on this for a little while.

2020-02-23 05:00 UTC, andrewtpoe commented
I've got a v2 feature set planned out in the issues. I'm going to re-target this at that branch and merge it in now. Thanks again for your contributions!

2020-02-23 05:01 UTC, andrewtpoe approved these changes

2020-02-23 05:02 UTC, merged